FGBook/config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users

  root 'home#index'

end

FGBook/app/models/book.rb
class Book < ActiveRecord::Base
	def complete_name
		"#{title}, #{author}"
	end
end

FGBook/app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
	
	validates_presence_of :email, :full_name, :locatino
	validates_format_of :email, with: EMAIL_REGEXP

	has_secure_password
end

FGBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

FGBook/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :price, :telephone, :description)
    end
end

FGBook/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@books = Book.take(3)
	end
end

FGBook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user, 
				notice: 'Cadastro criado com sucesso!'
		else
			render action: :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user, 
				notice: 'Cadastro atualizado com sucesso!'
		else
			render action: :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :full_name, :locatino, :password, :password_confirmation)
	end
end

FGBook/app/helpers/application_helper.rb
module ApplicationHelper
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag(
				:div,
				model.errors[attribute].first,
				class: 'error_message'
			)
		end
	end
end

FGBook/app/helpers/books_helper.rb
module BooksHelper
end

FGBook/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FGBook/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

FGBook/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Price</th>
      <th>Telephone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.price %></td>
        <td><%= book.telephone %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

FGBook/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

FGBook/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @book.telephone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

FGBook/app/views/home/index.html.erb
<h1>Livros recém postados</h1>

<ul>
	<% @books.each do |book| %>
		<li>
			<%= link_to "#{book.title}, #{book.author}", book %>
		</li>
	<% end %>
</ul>

FGBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FGBook</title>
	<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div id="header-wrap">
			<h1><%= link_to "FGBook", root_path %></h1>
			<nav>
				<ul>
					<li><%= link_to "Livros", books_path %></li>
					<li><%= link_to "Cadastro", new_user_path %></li>
				</ul>
			</nav>
		</div>
	</header>

	<div id="content">
		<% if notice.present? %>
			<p id="notice"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
			<p id="alert"><%= alert %></p>
		<% end %>

<%= yield %>

</body>
</html>

FGBook/app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
			Há erros no formulário, por favor verifique.
	</div>
<% end %>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :full_name %>
		<%= f.text_field :full_name %>
		<%= error_tag @user, :full_name %>
	</p>
	<p>
		<%= f.label :locatino %>
		<%= f.text_field :locatino %>
		<%= error_tag @user, :locatino %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
		<%= error_tag @user, :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<%= error_tag @user, :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
		<%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

FGBook/app/views/users/edit.html.erb
<h1>Editar perfil</h1>

<%= render 'form' %>

<% link_to "Voltar ao perfil", @user %>

FGBook/app/views/users/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

<%= link_to "Voltar", root_path %>

FGBook/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Perfil: <%= @user.full_name %></h1>

<ul>
	<li>Localização: <%= @user.locatino %></li>
</ul>

<%= link_to 'Editar Perfil', edit_user_path(@user) %>

<%= link_to 'Home', root_path %>